{% set name = "pandas-bokeh" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas-bokeh-{{ version }}.tar.gz
  sha256: 332e2bf2548640bbfa22bf683ba0820dbb427d4da8c129ef151124538a7640bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    # package imports itself are setup time :-/
    - bokeh >=2.0
    - pandas >=0.22.0
  run:
    - python >=3.7
    - bokeh >=2.0
    - pandas >=0.22.0

test:
  imports:
    - pandas_bokeh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PatrikHlobil/Pandas-Bokeh
  summary: Bokeh plotting backend for Pandas, GeoPandas & Pyspark
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
